### PR TITLE
Update ServiceMonitor for 2018 9B images

### PR DESCRIPTION
**Pull request by mcy94w**
Update ServiceMonitor.exe

### CODE REVIEW

**Comment by shirhatti** [comment]
You'll need to update the `FROM` line to point to MCR. I'd wait for that before merging this PR

**Comment by mcy94w** [comment]
> You'll need to update the `FROM` line to point to MCR. I'd wait for that before merging this PR

Are these old tags available on MCR yet?

**Comment by shirhatti** [comment]
> Are these old tags available on MCR yet?

Not yet

**Comment by mcy94w** [comment]
> > Are these old tags available on MCR yet?
> 
> Not yet

Then let's make the update when they are available.

**Comment by mcy94w** [comment]
@shhsu I will start the effort this week.

**Pull request merged**
