### PR TITLE
enable docker run microsoft/iis cmd

### PR DESCRIPTION
**Pull request by tg123**
enable
`
docker run microsoft/iis cmd
`

### CODE REVIEW

**Comment by shirhatti** [comment]
I'm looking at [Apache](https://github.com/docker-library/httpd/blob/master/2.4/Dockerfile#L81) and [Nginx](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L130) as well and does seem to be commonplace to specify the "entrypoint" of a base image using the `CMD` directive making it easy to overwrite.

@MichaelSimons @glennc Thoughts on making this change?

**Comment by StefanScherer** [comment]
As I've seen the nginx, httpd and mongo official Dockerfiles, I would also prefer to use `CMD` here.
@friism any suggestions how to share best practices on both Linux and Windows?

**Comment by MichaelSimons** [comment]
What is the version scheme for this image and the potential impact this change may have on existing users?

**Comment by shirhatti** [comment]
Versioning scheme for this repo is `microsoft/iis:[os-flavor]-[version]`

Seems like a low impact change, however the [ASP.NET images](https://github.com/microsoft/aspnet-docker) depend on this image they will be affected as well.

**Comment by glennc** [comment]
Are there ever any arguments you would want to pass to ServiceMonitor?

**Comment by shirhatti** [comment]
ServiceMonitor is generic enough to work with any service (that listens to Ctrl+C), but there's really no reason monitor any other service in the IIS/ASP.NET images.

**Comment by shhsu** [comment]
Actually mongo uses ENTRYPOINT instead of CMD. https://github.com/docker-library/mongo/blob/b37a4891feffeafb77febd2833d96b59cf28d6a8/3.0/Dockerfile#L51 There doesn't seem to be a consensus everywhere. From article https://www.ctl.io/developers/blog/post/dockerfile-entrypoint-vs-cmd/. The dockerfile was authored with the idea that user shouldn't need to modify the entry point. @tg123, could you provide some more detailed description of your motivation for the change?

**Comment by friism** [comment]
Can't you just run `docker run -ti --entrypoint cmd microsoft/iis`? cc @patricklang

**Comment by shirhatti** [comment]
> Can't you just run `docker run -ti --entrypoint cmd microsoft/iis`

Yes. This currently works

**Comment by tg123** [comment]
Hi @shufan 

I checked the Dockerfile you referred, it uses `CMD` not  `ENTRYPOINT`.

```
COPY docker-entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 27017

CMD ["mongod"]
```

As I know most docker images use entrypoint to do some init works that must be called when container starts.
The "ServiceMonitor" here works like a daemon on Linux, as a result, I prefer to use it in CMD.

And any detailed reason why user should not change the entrypoint?

**Comment by shhsu** [comment]
Technically docker-mongo uses ENTRYPOINT and CMD is only there to provide the input argument.

It's true that ServiceMonitor serves like a daemon currently therefore CMD would make sense. However I know that there's some work going on for w3svc to be called directly. In that case ENTRYPOINT makes sense over CMD. So this is another reason that ENTRYPOINT was chosen.

@shirhatti should have more context on this

**Pull request closed without merging**
